#pragma config(Sensor, in1,    linef,          sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lights,         sensorReflection)
#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump,           sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, red,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flash,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           right1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           left1,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 4
  Team Members: Joy Lin, Vencel Villanueva
  Date: 11/4/21
  Section: Period 4


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces


while(1==1) //part 1
{
		if(SensorValue(lights)>700)
		{
				turnFlashlightOn(flash,127);
			}
			if(SensorValue(lights)<=700)
			{
					turnFlashlightOff(flash);//if light sensor value is above 700, flashlight will turn on, if below the flashlight will turn on
		}
	}
	while(1==1) //part 2
	{
		while (SensorValue(limit)==1)// while the limit switch is pressed, and its dark it will turn on the light, if it isn't then it will turn off
		{
			if (SensorValue(lights)>700)
			{
				turnFlashlightOn(flash,127);
			}
			else
			{
				turnFlashlightOff(flash);
			}
		}
		turnFlashlightOff(flash);
	}
	while(1==1)//part 3
	{
		while (SensorValue(bump)==1)//when the bump switch is pressed, then the led will turn on and off every .6 seconds.
		{
			turnLEDOn(red);
			wait(0.3);
			turnLEDOff(red);
			wait(0.3);
		}
	}
while(1==1)//part 4
{
	if (SensorValue(bump)==1) //when the bump is pressed the motor will start turning until the bump switch is not pressed.
	{
		startMotor(left1,127);
	}
	else
	{
		startMotor(left1,-127);
	}
}
while (1==1) //part 4b
{
	if (SensorValue(linef)<400)//the servo will turn to the right if the line follower is not covered by the hand, if it is then the servo will turn left.
	{
		setServo(servo,-127);
	}
	else
	{
		setServo(servo,127);
	}
}
while (1==1) //part 4c
{
	if (SensorValue(bump)==1)//just as the same as part 4b but in the bump switched is pressed then the servo will reset.
	{
		if(SensorValue(linef)<400)
		{
			setServo(servo,-127);
		}
		else
		{
			setServo(servo,127);
		}
	}
	else
	{
		setServo(servo,0);
	}
}
while (1==1) //part 4d
{
	if (SensorValue(bump)==1)//if the bump switch is pressed then the left motor will turn foward, if not then it will turn backward. If the limit switch is pressed the right motor will turn foward and the right motor will turn back if it isn't pressed
	{
		startMotor(left1,127);
	}
	else
	{
		startMotor(left1,-127);
	}
	if(SensorValue(limit)==1)
	{
		startMotor(right1,127);
	}
	else
	{
		startMotor(right1,-127);
	}
}





















}
