#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           Leftmotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Activity 2
  Team Members: Joy Lin, Vencel Villanueva
  Date: 10/29/21
  Section: Period 4


  Task Description:


  Pseudocode:
Part 1; 	Controlling Ideas
turn the LED on and off twice, at 1 second intervals
*/

task main()
{                                     //Program begins, insert code within curly braces
turnLEDOff(led);
wait(1);
turnLEDOn(led);
wait(1);
turnLEDOff(led);
wait(1);
turnLEDOn(led);
wait(1);
turnLEDOff(led);
                     startMotor(RightMotor, 50);// right motor moves at 50 speed (1a)  Part 2
wait(5);
stopMotor(port2);
wait(1);
startMotor(RightMotor, 50);
startMotor(Leftmotor, 50);//left motor moves at 50 speed (1b)
wait(5);
stopMotor(port2);
stopMotor(port3);
wait(1);
startMotor(RightMotor, -50);// right motor moves at 50 speed (3a)
startMotor(Leftmotor, -50);//left motor moves at 50 speed
wait(5);//added 5 second wait time for each activity to make it more organized
                 startMotor(RightMotor, 50);//turns right motor at 50 speed for 5 seconds   (5a)            Part 3
wait(5);
stopMotor(port2);
wait(3);
startMotor(Leftmotor, -35);//turns left motor at 35 speed at reverse for 2.5 seconds (1a)
wait(2.5);
stopMotor(port3);
wait(3);
startMotor(Leftmotor, 70);//turns both motors at 70 speed for 7.25 seconds (1b)
startMotor(RightMotor, 70);
wait(7.25);




}
