#pragma config(Sensor, in1,    linefollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potention,      sensorPotentiometer)
#pragma config(Sensor, in3,    light,          sensorReflection)
#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump,           sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flash,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           right1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           left1,         tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Test
Team Members: Vencel V
Date: 11/18/21
Section: Period 5


Task Description:


Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	while(1==1)
	{
		while(SensorValue(limit)==1)
		{
			startMotor(left1, 60);
		}
	}
	if(SensorValue(sonar)<8)
	{
		turnFlashlightOn(flash,80);
	}
	else(SensorValue(sonar)>8);
	{
		turnFlashlightOff(flash);
	}
}
